config/routes.rb
Rails.application.routes.draw do

  post '/ajax/products/delete', to:'products#delete'
  post '/ajax/shoppingcart/delete', to:'shoppingcart#delete_item'

  scope '/(:locale)', defaults: { locale: 'en' }, constraints: { locale: /en|es/ } do
    root to: 'home#index'
    devise_for :users
    resources :users
    resources :products
    resources :charges
    get '/my-account', to:'account#index'
    get '/user/profile/:id', to:'users#public_profile', as: 'public_profile'
    get '/search', to:'search#index'
    get '/basket', to:'shoppingcart#basket', as: 'basket'
    get '/checkout', to:'shoppingcart#checkout', as: 'checkout'
    get '/products/details/:id', to:'products#details', as: 'products_details'
    get '/search/search_near_json', to:'search#search_near_json'
    get '404', to: 'application#page_not_found', as: 'not_found'
    post '/shoppingcart/add_item', to:'shoppingcart#add_item', as:'add_item'
    post '/shoppingcart/new_purchase', to:'shoppingcart#new_purchase', as: 'new_purchase'
    post '/account/update_image', to:'account#update_image', as: 'update_user_image'
    post '/products/new_comment', to:'products#new_comment', as: 'new_comment'
  end
end

app/controllers/shoppingcart_controller.rb
class ShoppingcartController < ApplicationController

  before_filter :authenticate_user!, :only => [:checkout]
  before_action do
    @session_id = session["session_id"];
    @basket_service = ShoppingCartService.new(@session_id)
  end

  def add_item
    product_id = params[:product_id]
    quantity = params[:quantity]
    @basket_service.add_item(product_id,quantity)
    redirect_to products_details_path id:product_id
  end

  def delete_item
    product_id = params[:id]
    @basket_service.delete_item(product_id)
    render json: {status:200}
  end

  def basket
    @products = self.get_basket_products
    @total = @basket_service.get_total
  end

  def checkout
    @purchase = Purchase.find params[:ref].to_i
    @total = @purchase.total
    @products = []
    @purchase.items.each do |item|
      product = Product.find item.product_id
      @products.push([product,item.quantity])
    end
    @products
  end

  def new_purchase
    purchase = @basket_service.new_purchase current_user
    redirect_to checkout_path ref:purchase.id
  end

  protected
  def get_basket_products
    @products = []
    basket = @basket_service.get_basket
    basket.items.each do |item|
      product = Product.find item.product_id
      stock_service = StockService.new product
      #get real stock
      product.stock = stock_service.get_stock
      @products.push([product,item.quantity])
    end
    @products
  end
  
end

app/views/shoppingcart/basket.html.erb
<section class="cart">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 style="margin-bottom:30px;"><%=t('shopping_cart')%></h1>
      </div>
    </div>
    <%if @products.count == 0%>
    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-info text-center">
          Yours basket is empty
        </div>
      </div>
    </div>
    <%end%>
    <div class="row">
      <% @products.each do |item|%>
        <article class="media col-md-6 cart-product">
          <%@image = asset_url('noPicture.png')%>
          <%  @image = item[0].images.first.original  if item[0].images.first%>
          <a class="pull-left" href="<%= products_details_path id:item[0].id%>">
            <img style="max-width:170px;" data-img="<%=@image%>" src="<%=@image%>" class="media-object img-responsive" alt="<%= item[0].title %>"/>
          </a>
          <div class="media-body">
            <div class="well well-lg">
              <h4 class="media-heading text-uppercase reviews"><%= item[0].title%></h4>
              <p><%= item[0].short_description%>
              </p>
              <ul>
                <li class="color-red"><%= item[0].price %> €</li>
                <li>Quantity: <%= item[1] %></li>
              </ul>
              <div class="delete text-right" data-id="<%=item[0].id%>">Remove item</div>
            </div>
          </div>
        </article>
      <%end%>
    </div>
    <%if @products.count > 0%>
    <div class="row">
      <div class="col-md-12 text-right basket-total">
        <hr>
        Total: <%=@total%> €
      </div>
    </div>
      <div class="row" style="margin:30px 0;margin-right:-15px;">
        <div class="col-md-8"></div>
        <div class="col-md-4">
          <form action="<%=new_purchase_path%>" method="post">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <button type="submit" class="btn btn-red form-control"><%= t('checkout')%></button>
          </form>
        </div>
      </div>
    <%end%>
  </div>
</section>
<%content_for :head do%>
  <title><%= t('basket_meta_title')%></title>
  <meta name="description" content="<%= t('basket_meta_description')%>"/>
<%end%>
<%content_for :search do%>
  <%=render 'search'%>
<%end%>

app/views/shoppingcart/checkout.html.erb
<section class="cart">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 style="margin-bottom:30px;"><%=t('summary')%></h1>
      </div>
    </div>
    <div class="row">
      <% @products.each do |item|%>
        <article class="media col-md-6 cart-product">
          <%@image = asset_url('noPicture.png')%>
          <%  @image = item[0].images.first.original  if item[0].images.first%>
          <a class="pull-left" href="<%= products_details_path id:item[0].id%>">
            <img style="max-width:170px;" data-img="<%=@image%>" src="<%=@image%>" class="media-object img-responsive" alt="<%= item[0].title %>"/>
          </a>
          <div class="media-body">
            <div class="well well-lg">
              <h4 class="media-heading text-uppercase reviews"><%= item[0].title%></h4>
              <p><%= item[0].short_description%>
              </p>
              <ul>
                <li class="color-red"><%= item[0].price %> €</li>
                <li>Quantity: <%= item[1] %></li>
              </ul>
            </div>
          </div>
        </article>
      <%end%>
    </div>
    <div class="row">
      <div class="col-md-12 text-right basket-total">
        <hr>
        Total: <%=@total%> €
      </div>
    </div>
    <div class="pay" style="margin-bottom:30px;">
      <%= form_tag charges_path do %>
        <article style="margin-bottom:30px;">
          <h2>Payment method</h2>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>

        </article>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Tappeat order"
          data-shipping-address = true
          data-amount= <%=@total * 100%>
          data-email = "<%=current_user.email%>"
          data-locale="auto"></script>
      <% end %>
    </div>
  </div>
</section>
<%content_for :search do%>
  <%=render 'search'%>
<%end%>
<%content_for :head do%>
  <title><%= t('checkout_meta_title')%></title>
  <meta name="description" content="<%= t('checkout_meta_description')%>"/>
<%end%>