config/routes.rb
Rails.application.routes.draw do

  post '/ajax/products/delete', to:'products#delete'
  post '/ajax/shoppingcart/delete', to:'shoppingcart#delete_item'

  scope '/(:locale)', defaults: { locale: 'en' }, constraints: { locale: /en|es/ } do
    root to: 'home#index'
    devise_for :users
    resources :users
    resources :products
    resources :charges
    get '/my-account', to:'account#index'
    get '/user/profile/:id', to:'users#public_profile', as: 'public_profile'
    get '/search', to:'search#index'
    get '/basket', to:'shoppingcart#basket', as: 'basket'
    get '/checkout', to:'shoppingcart#checkout', as: 'checkout'
    get '/products/details/:id', to:'products#details', as: 'products_details'
    get '/search/search_near_json', to:'search#search_near_json'
    get '404', to: 'application#page_not_found', as: 'not_found'
    post '/shoppingcart/add_item', to:'shoppingcart#add_item', as:'add_item'
    post '/shoppingcart/new_purchase', to:'shoppingcart#new_purchase', as: 'new_purchase'
    post '/account/update_image', to:'account#update_image', as: 'update_user_image'
    post '/products/new_comment', to:'products#new_comment', as: 'new_comment'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  protect_from_forgery with: :exception

  def set_locale
    I18n.locale = params[:locale].to_sym if params[:locale] != nil
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def products_in_basket
    basket = Basket.find_by session: session["session_id"];
    items_in_basket = 0
    if basket
      items_in_basket = basket.items.reduce(0) do |sum, item|
        sum += item.quantity
      end
    end
  end
  
end

app/views/application/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        Copyright © 2016 TappEat 
      </div>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<header class="header">
    <div class="row">
      <div class="col-md-3">
        <a class="logo" href="<%=root_path%>"><img width="44" height="47"  src="<%=asset_url("marker_white.svg") %>" alt="logo">Tappeat</a>
      </div>
      <div class="col-md-5 hidden-xs hidden-sm" style="position:relative;left:15px;padding-right:0;">
        <div class="form-inside">
          <%= yield :search%>
        </div>
      </div>
      <div class="col-md-1">
        <%if !products_in_basket.nil? && products_in_basket > 0%>
          <a class="cart-items" href="<%= basket_path%>">
            <%=products_in_basket%>
            <%= t('items')%>
          </a>
        <%end%>
      </div>
      <div class="col-md-3 text-right hidden-xs">
        <nav class="auth-links">
          <ul>
            <%= render 'nav_links_for_auth' %>
          </ul>
        </nav>
      </div>
    </div>
</header>
<%= render 'modal_sign_up'%>
<%= render 'modal_sign_in'%>

app/views/application/_modal_sign_in.html.erb
<!-- sign up modal -->
<div class="modal fade user" id="modalSignIn" tabindex="-1" role="dialog" aria-labelledby="modalSignInLabel">
  <div class="modal-admin" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="authform">
          <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :role => 'form'}) do |f| %>
            <h3>Sign in</h3>
            <%= devise_error_messages! %>
            <div class="form-group">
              <%- if devise_mapping.registerable? %>
              <% end -%>
              <%= f.label :email %>
              <%= f.email_field :email, :autofocus => true, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
              <%= f.submit 'Sign in', :class => 'btn btn-primary form-control' %>
              <% if devise_mapping.rememberable? -%>
                <div class="checkbox" style="width:150px">
                  <label>
                    <%= f.check_box :remember_me %> Remember me
                  </label>
                </div>
              <% end -%>
              <%- if devise_mapping.recoverable? %>
                <%= link_to "Forgot password?", new_password_path(resource_name), class: 'text-center' %>
              <% end -%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_modal_sign_up.html.erb
<!-- sign up modal -->
<div class="modal fade user" id="modalSignUp" tabindex="-1" role="dialog" aria-labelledby="modalSignUpLabel">
  <div class="modal-admin" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <div class="authform">
          <%= form_for(resource,:as => resource_name, :url => registration_path(resource_name), :html => { :role => 'form'}) do |f| %>
            <h3>Sign up</h3>
            <%= devise_error_messages! %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
             <%= f.submit 'Sign up', :class => 'btn btn-red form-control' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to current_user.name, my_account_path  %>
    <%@image = asset_url('profile.png')%>
    <%@image = current_user.images.first.original if current_user.images.first %>
    <a href="<%=my_account_path %>"><img class="img-circle" width="40" height="40s" src="<%=@image%>" alt="profile logo"></a>
  </li>
  <li><%= link_to t('sign_out'), destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li>
    <a href="#" data-toggle="modal" data-target="#modalSignUp" class="btn btn-white">  <%=  t('become_a_cook')%></a>
  <li>
    <a href="#" data-toggle="modal" data-target="#modalSignIn">  <%=  t('sign_in')%></a>
  </li>
<% end %>

app/views/application/_product.html.erb
<article class="col-md-6 col-lg-4 col-sm-6 animated zoomIn product-container">
  <div class="product">
    <%@image = asset_url('noPicture.png')%>
    <%@image = product.images.first.original  if product.images.count > 0%>
    <img width="358" height="230" class="header-bg img-responsive" src="<%= @image %>" alt="<%= product.title %>">
    <div class="avatar">
      <% @profile_image = asset_url('profile.png')%>
      <%  @profile_image = product.user.images.first.original  if product.user.images.count > 0%>
      <img width="100" height="100" src="<%=@profile_image%>" alt="user photo" />
    </div>
      <div class="content">
        <h3><%= product.title %></h3>
        <p><%= product.short_description%></p>
        <span class="price color-red"><%= product.price%> € / <small>tappeat</small></span>
        <a href="<%= products_details_path :id => product.id%>" class="btn btn-buy btn-red"><%=t('details')%></a>
      </div>
  </div>
</article>

app/views/application/_product_form.html.erb
<%= form_for @product , method: "POST", url: {controller:"products", action: "create"} do |f| %>
  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title,class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :short_description%> <small>Max 100 chars</small>
    <%= f.text_field :short_description, class:"form-control" %>
    <span class="count">0</span>
  </div>
  <div class="form-group">
    <%= f.label :category_id%>
    <%= f.select(:category_id, @categories.collect{|u| [u.name, u.id]},{},{ class: 'form-control' })-%>
  </div>
  <div class="form-group">
    <%= f.label :price%>
    <%= f.text_field :price, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :expiration%>
    <%= f.datetime_local_field :expiration, class:"form-control",style:"width:300px;" %>
  </div>
  <div class="form-group">
    <%= f.label :stock%>
    <%= f.number_field :stock, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :id%>
    <%= f.label :description%>
    <%= f.text_area :description,rows:7, class:"form-control" %>
  </div>
  <label>Location</label><small> (Search in the box bellow) </small>
  <input id="pac-input" class="controls" type="text" placeholder="Search Box">
  <div id="product-map"></div>
  <div class="form-group">
    <label>Product image</label>
    <%= f.file_field :image %>
  </div>
  <input type="hidden" name="product[lat]" id="product_lat">
  <input type="hidden" name="product[lng]" id="product_lng">
  <%= f.submit "Create", class:"btn btn-red pull-right" %>
<% end %>

app/views/application/_search.html.erb
<form action="/search" id="searchForm">
  <div class="col-md-8 col-sm-8">
    <div class="form-group">
      <input type="hidden" name="lat" id="inputLat"/>
      <input type="hidden" name="lng" id="inputLng">
      <input type="text" class="form-control" id="autocomplete" placeholder="<%=t('search_placeholder')%>">
    </div>
  </div>
  <div class="col-md-4 col-sm-4">
  <button id="btnSearch" type="submit" class="btn btn-primary form-control"><%=t('im_hungry')%></button>
</div>
</form>

app/views/application/_user_address_form.html.erb
<form>
  <div class="form-group">
    <label>Address</label>
    <input type="text" name="address" class="form-control">
  </div>
  <div class="form-group">
    <label>Country</label>
    <input type="text" name="country" class="form-control">
  </div>
  <div class="form-group">
    <label>Zip Code</label>
    <input type="text" name="zip" class="form-control">
  </div>
</form>

app/views/application/page_not_found.html.erb
<section class="error not-found">
  <h1><%=t('not_found_title')%></h1>
  <img class="img-responsive" src="<%=asset_url('hambre')%>" alt="">
</section>
<%content_for :search do%>
  <%=render 'search'%>
<%end%>