config/routes.rb
Rails.application.routes.draw do

  post '/ajax/products/delete', to:'products#delete'
  post '/ajax/shoppingcart/delete', to:'shoppingcart#delete_item'

  scope '/(:locale)', defaults: { locale: 'en' }, constraints: { locale: /en|es/ } do
    root to: 'home#index'
    devise_for :users
    resources :users
    resources :products
    resources :charges
    get '/my-account', to:'account#index'
    get '/user/profile/:id', to:'users#public_profile', as: 'public_profile'
    get '/search', to:'search#index'
    get '/basket', to:'shoppingcart#basket', as: 'basket'
    get '/checkout', to:'shoppingcart#checkout', as: 'checkout'
    get '/products/details/:id', to:'products#details', as: 'products_details'
    get '/search/search_near_json', to:'search#search_near_json'
    get '404', to: 'application#page_not_found', as: 'not_found'
    post '/shoppingcart/add_item', to:'shoppingcart#add_item', as:'add_item'
    post '/shoppingcart/new_purchase', to:'shoppingcart#new_purchase', as: 'new_purchase'
    post '/account/update_image', to:'account#update_image', as: 'update_user_image'
    post '/products/new_comment', to:'products#new_comment', as: 'new_comment'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :user
  belongs_to :category
  belongs_to :place
  belongs_to :purchase
  has_many :comments
  has_many :images
  validates :title, presence: true
  validates :short_description, presence: true
  validates :price, presence: true
  validates :expiration, presence: true
  validates :stock, presence: true
  validates :description, presence: true

  def self.get_random_featured quantity
    limit(quantity).where('featured = true').order("RANDOM()")
  end

  def self.search_near lat, lng
    @products = []
    places = Place.where("acos(sin(#{lat}) * sin(lat) + cos(#{lat}) * cos(lat) * cos(lng - (#{lng}))) * 6371 <= 3").order("created_at DESC")
    places.each do |place|
      @products.push(place.products)
    end
    @products
  end

  def self.get_random_by_category categoryId, quantity
    limit(quantity).where("category_id = #{categoryId}").order("RANDOM()")
  end

  def by_user user_id
    where("user_id = ?", user_id)
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, :except => [:details, :get_products]

  def details
    @product = Product.find_by id: params[:id]
    unless @product
     redirect_to not_found_path
     return
    end
    @related = Product.get_random_by_category @product.category.id, 3
    @related = @related.where("id !=#{@product.id}")
    @comments = @product.comments.limit(5).order("RANDOM()")
    stock_service = StockService.new(@product)
    @stock = stock_service.get_stock
  end

  def get_products id_user
    user = User.find id_user
    if current_user != user
      render json: "error"
      return
    end
    products = Products.where('user_id = ?', id_user)
    render json: products
  end

  def create
    params = product_params
    product = ProductService.update_product current_user.id, params
    redirect_to controller:"account", action:"index"
  end

  def edit
    @product = Product.find params[:id]
    @categories = Category.all
  end

  def delete
    ProductService.delete params[:id]
    render json: {status:200}
  end

  def new_comment
    product = Product.find params[:id_product]
    unless product
     redirect_to not_found_path
     return
    end
    unless current_user
       redirect_to not_found_path
       return
    end
    # por ahora no hago moderación de comentarios.
    Comment.create(user:current_user,product:product,content: params[:content],published:true,new:false)
    redirect_to products_details_path id:product.id
  end

  private
  def product_params
    params.require(:product).permit(:id,:title, :short_description,:category_id, :price,:expiration,:description,:image,:stock,:lat,:lng)
  end
  
end

app/views/products/details.html.erb
<%content_for :head do%>
  <title><%=@product.title%></title>
  <meta name="description" content="<%=@product.short_description%>"/>
<%end%>
<%content_for :search do%>
  <%=render 'search'%>
<%end%>
<%content_for :page_scripts do%>
  <script src="<%=asset_url('basket.js')%>"></script>
<%end%>
<section class="product-details">
  <div class="container">
    <div class="row">
      <article>
        <div class="col-md-5">
          <%@image = asset_url('noPicture.png')%>
          <%  @image = @product.images.first.original  if @product.images.first%>
          <img class="img-responsive" src="<%=@image%>" alt="<%=@product.title%>" />
          <ul>
            <li class="media">
              <%=t('cook')%>:
              <a href="<%=public_profile_path id:@product.user.id%>">
                <% @current_profile = asset_url('profile.png')%>
                <%  @current_profile = @product.user.images.first.original  if @product.user.images.count > 0%>
                <img style="display:inline;margin-left:10px;margin-right:10px;" width="70" class="media-object img-circle" src="<%= @current_profile%>" alt="profile">
              </a>
            </li>
            <li><%=t('category_li')%>: <%=@product.category.name%></li>
            <%if @product.rating > 0%>
              <li>
                <%for i in 1..@product.rating%>
                  <span class="rating-star">&#9734;</span>
                <%end%>
              </li>
            <%end%>
            <li class="product-price"><%=t('price')%>: <span class="color-red"><%=@product.price%> € / </span> <small class="color-red"> <%=t('tappeat')%></small></li>

          </ul>
          <form action="<%=add_item_path%>" method="POST">
            <div class="row">
              <%if @stock > 0%>
                <div class="col-md-3">
                  <select class="form-control" name="quantity" id="selectQuantity">
                    <%for i in 1..@stock%>
                      <option value="<%=i%>"><%=i%></option>
                    <%end%>
                  </select>
                  <input type="hidden" name="product_id" value="<%=@product.id%>">
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                </div>
                <div class="col-md-9">
                <button type="submit" class="form-control btn btn-red"><%=t('add_to_cart')%></button>
                </div>
              <%else%>
              <div class="col-md-12">
              <div class="alert alert-info text-center"><%=t('no_stock')%></div>
              </div>
              <%end%>
            </div>
          </form>
        </div>
        <div class="col-md-7">
          <h1><%= @product.title %></h1>
          <p><%=@product.description%></p>
          <%if current_user%>
          <hr>
            <h2><%=t('gustado_producto')%></h2>
            <form action="<%=new_comment_path%>" method="post" class="comment-form">
              <div class="form-group">
                <label><%=t('content')%></label>
                <textarea name="content" required="required" rows="5" class="form-control"></textarea>
              </div>
              <input type="hidden" name="id_product" value="<%=@product.id%>">
              <button type="submit" class="btn btn-red pull-right"><%=t('comment')%></button>
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            </form>
          <%end%>
        </div>
      </article>
    </div>
    <%if @comments.any?%>
      <div class="row">
        <div class="col-md-12 comments">
          <h2><%=t('users_say')%></h2>

            <ul class="media-list">
              <%@comments.each do |comment| %>
              <li class="media">
                <a class="pull-left" href="#">
                  <% @profile_image = asset_url('profile.png')%>
                  <%  @profile_image = comment.user.images.first.original  if comment.user.images.count > 0%>
                  <img width="70" class="media-object img-circle" src="<%= @profile_image%>" alt="profile">
                </a>
                <div class="media-body">
                  <div class="well well-lg">
                      <h4 class="media-heading text-uppercase reviews"><%=comment.user.name%></h4>
                      <p class="media-comment">
                        <%= comment.content%>
                      </p>
                  </div>
                </div>
              </li>
              <%end%>
            </ul>
        </div>
      </div>
    <%end%>
  </div>
</section>
<%if @related.any?%>
  <section class="related">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2><%= t('other_products')%> </h2>
        </div>
      </div>
      <div class="row">
        <%@related.each do |product|%>
          <%= render 'product', product:product%>
        <%end%>
      </div>
    </div>
  </section>
<%end%>

app/views/products/edit.html.erb
<section class="edit-product">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Edit product</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= render 'product_form' %>

      </div>
    </div>
  </div>
</section>
<% #page info %>
<%content_for :search do%>
  <%=render 'search'%>
<%end%>
<%content_for :page_scripts do%>
  <script src="<%= asset_url('mapsearch.js')%>"></script>
  <script>
  $(document).ready(function(){

  })
  </script>
<%end%>