config/routes.rb
Rails.application.routes.draw do

  post '/ajax/products/delete', to:'products#delete'
  post '/ajax/shoppingcart/delete', to:'shoppingcart#delete_item'

  scope '/(:locale)', defaults: { locale: 'en' }, constraints: { locale: /en|es/ } do
    root to: 'home#index'
    devise_for :users
    resources :users
    resources :products
    resources :charges
    get '/my-account', to:'account#index'
    get '/user/profile/:id', to:'users#public_profile', as: 'public_profile'
    get '/search', to:'search#index'
    get '/basket', to:'shoppingcart#basket', as: 'basket'
    get '/checkout', to:'shoppingcart#checkout', as: 'checkout'
    get '/products/details/:id', to:'products#details', as: 'products_details'
    get '/search/search_near_json', to:'search#search_near_json'
    get '404', to: 'application#page_not_found', as: 'not_found'
    post '/shoppingcart/add_item', to:'shoppingcart#add_item', as:'add_item'
    post '/shoppingcart/new_purchase', to:'shoppingcart#new_purchase', as: 'new_purchase'
    post '/account/update_image', to:'account#update_image', as: 'update_user_image'
    post '/products/new_comment', to:'products#new_comment', as: 'new_comment'
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    @amount = 500
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/views/charges/create.html.erb
<section class="payed section-padded">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 style="margin-bottom:30px;">Thanks, your purchase has been paid correctly</h1>
        <a href="<%=my_account_path%>" class="btn btn-red">View purchase</a>
      </div>
    </div>
  </div>
</section>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-amount="500"
    data-locale="auto"></script>
<% end %>